<a href="https://colab.research.google.com/github/TakeYourHearts/TakeYourHearts/blob/estudo/101_Numpy_Exercises_f_DA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://www.machinelearningplus.com/python/101-numpy-exercises-python/

1. Import numpy as np and see the version

In [3]:
import numpy as np

np.__version__


'2.0.2'

2. How to create a 1D array?

In [6]:
a = np.array([0,1,2,3,4,5,6,7,8,9])

a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

3. Create a 3×3 numpy array of all True’s


In [8]:
a = np.array([[1,2,3],[1,2,3]])

a

array([[1, 2, 3],
       [1, 2, 3]])

4. How to extract items that satisfy a given condition from 1D array?

Q. Extract all odd numbers from


In [20]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])



arr_impar = np.where(arr % 2 != 0)

arr_impar

(array([1, 3, 5, 7, 9]),)

5. How to replace items that satisfy a condition with another value in numpy array?
Difficulty Level: L1

Q. Replace all odd numbers in arr with -1



In [24]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

arr[arr % 2 != 0 ] = -1

arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

6. How to replace items that satisfy a condition without affecting the original array?
Difficulty Level: L2

Q. Replace all odd numbers in arr with -1 without changing arr

In [36]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


out = np.where(arr %2 != 0,-1,arr)

print(arr)
out

[0 1 2 3 4 5 6 7 8 9]


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

7. How to reshape an array?
Difficulty Level: L1

    Q. Convert a 1D array to a 2D array with 2 rows

In [40]:
arr = np.arange(10)

arr = np.reshape(arr,(2,5))

print(arr)

[[0 1 2 3 4]
 [5 6 7 8 9]]


8. How to stack two arrays vertically?
Difficulty Level: L2

Q. Stack arrays a and b vertically

In [45]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)


arr = np.concatenate((a,b))
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

9. How to stack two arrays horizontally?
Difficulty Level: L2

Q. Stack the arrays a and b horizontally.

In [48]:
a = np.arange(10).reshape(2,-1)

b = np.repeat(1, 10).reshape(2,-1)

arr = np.concatenate((a,b),axis=1)
arr

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

10. How to generate custom sequences in numpy without hardcoding?
Difficulty Level: L2

Q. Create the following pattern without hardcoding. Use only numpy functions and the below input array a.

In [56]:
a = np.array([1,2,3])

arr_1 = np.repeat(a,3)
arr_2 = np.tile(a,3)

arr  = np.concatenate((arr_1,arr_2))
arr

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

1. How to get the common items between two python numpy arrays?
Difficulty Level: L2

    Q. Get the common items between a and b

In [62]:
a = np.array([1,2,3,2,3,4,3,4,5,6])

b = np.array([7,2,10,2,7,4,9,4,9,8])

arr = np.intersect1d(a,b)

arr

array([2, 4])